print("Hello Git!")
print("I'm learning git")
print("Git is very easy")
print("This is my feature")
print("This is my feature2")
print("Day 3 Git practice")
print("Learning git reset")
print("Learning git stash")
print("Change made directly on GitHub")
print("Feature 3 work")
print("Day 5 team workflow")
print("Day 5 second commit")

